[settings]
# Mise should ignore "idiomatic version files"
# and consider this toml file as the only source of truth
# Cf: https://mise.jdx.dev/configuration.html#idiomatic-version-files
legacy_version_file = false

[tools]
python = "3.13"
poetry = "2.2"

[env]
_.file = '.env'
_.python.venv = { path = ".venv", create = false }


[tasks.test]
description = "üêç Run tests"
run = "pytest -s"
